apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-nfs-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-nfs-pod
  template:
    metadata:
      labels:
        app: nginx-nfs-pod
    spec:
      containers:
      - name: nginx-nfs
        image: nginx:1.20
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
        - name: html
          persistentVolumeClaim:
            claimName: nginx-nfs-pvc-html
