apiVersion: v1
kind: Service
metadata:
  name: nginx-nfs-server
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31010
  selector:
    app: nginx-nfs-pod
