apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-nfs-pvc-html
  namespace: default
spec:
  storageClassName: nfs-server
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
