kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-main
  namespace: maintenance
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "delete"]
