kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding-main
  namespace: maintenance
subjects:
- kind: User
  name: main
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: role-main
  apiGroup: rbac.authorization.k8s.io
